system:
  #certificateFilePath: "parsec:object=ggeulachtoken;type=cert"
  #privateKeyPath: "/private.pem.key"
  # the object in the URI is the actual label given the private key
  #privateKeyPath: "parsec:object=ggeulachtoken;type=cert"
  privateKeyPath: "/privKey.key"
  certificateFilePath: "/thingCert.crt"
  rootCaPath: "/AmazonRootCA1.pem"
  rootpath: ""
services:
  aws.greengrass.crypto.ParsecProvider:
    configuration:
      name: "greengrass-parsec-plugin"
      derRootCaPath: ...
      derCertPath: ...
      parsecSocket: "/run/parsec/parsec.sock"
